
package com.jhg.marketing.web.util.note;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LinkWSSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LinkWSSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "msg.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "msg.HelloWorldResponse")
    public String helloWorld();

    /**
     * 
     * @param corpID
     * @param mobile
     * @param pwd
     * @param cell
     * @param content
     * @param sendTime
     * @return
     *     returns int
     */
    @WebMethod(operationName = "BatchSend", action = "http://tempuri.org/BatchSend")
    @WebResult(name = "BatchSendResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BatchSend", targetNamespace = "http://tempuri.org/", className = "msg.BatchSend")
    @ResponseWrapper(localName = "BatchSendResponse", targetNamespace = "http://tempuri.org/", className = "msg.BatchSendResponse")
    public int batchSend(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "Content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "Cell", targetNamespace = "http://tempuri.org/")
        String cell,
        @WebParam(name = "SendTime", targetNamespace = "http://tempuri.org/")
        String sendTime);

    /**
     * 
     * @param corpID
     * @param pwd
     * @param cell
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetReportFail", action = "http://tempuri.org/GetReportFail")
    @WebResult(name = "GetReportFailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetReportFail", targetNamespace = "http://tempuri.org/", className = "msg.GetReportFail")
    @ResponseWrapper(localName = "GetReportFailResponse", targetNamespace = "http://tempuri.org/", className = "msg.GetReportFailResponse")
    public String getReportFail(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "cell", targetNamespace = "http://tempuri.org/")
        String cell);

    /**
     * 
     * @param corpID
     * @param mobile
     * @param memo
     * @param corpName
     * @param tel
     * @param pwd
     * @param linkMan
     * @param email
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Reg", action = "http://tempuri.org/Reg")
    @WebResult(name = "RegResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Reg", targetNamespace = "http://tempuri.org/", className = "msg.Reg")
    @ResponseWrapper(localName = "RegResponse", targetNamespace = "http://tempuri.org/", className = "msg.RegResponse")
    public int reg(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "CorpName", targetNamespace = "http://tempuri.org/")
        String corpName,
        @WebParam(name = "LinkMan", targetNamespace = "http://tempuri.org/")
        String linkMan,
        @WebParam(name = "Tel", targetNamespace = "http://tempuri.org/")
        String tel,
        @WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "Email", targetNamespace = "http://tempuri.org/")
        String email,
        @WebParam(name = "Memo", targetNamespace = "http://tempuri.org/")
        String memo);

    /**
     * 
     * @param corpID
     * @param newPwd
     * @param pwd
     * @return
     *     returns int
     */
    @WebMethod(operationName = "UpdPwd", action = "http://tempuri.org/UpdPwd")
    @WebResult(name = "UpdPwdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdPwd", targetNamespace = "http://tempuri.org/", className = "msg.UpdPwd")
    @ResponseWrapper(localName = "UpdPwdResponse", targetNamespace = "http://tempuri.org/", className = "msg.UpdPwdResponse")
    public int updPwd(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "NewPwd", targetNamespace = "http://tempuri.org/")
        String newPwd);

    /**
     * 
     * @param corpID
     * @param mobile
     * @param memo
     * @param corpName
     * @param tel
     * @param pwd
     * @param linkMan
     * @param email
     * @return
     *     returns int
     */
    @WebMethod(operationName = "UpdReg", action = "http://tempuri.org/UpdReg")
    @WebResult(name = "UpdRegResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdReg", targetNamespace = "http://tempuri.org/", className = "msg.UpdReg")
    @ResponseWrapper(localName = "UpdRegResponse", targetNamespace = "http://tempuri.org/", className = "msg.UpdRegResponse")
    public int updReg(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "CorpName", targetNamespace = "http://tempuri.org/")
        String corpName,
        @WebParam(name = "LinkMan", targetNamespace = "http://tempuri.org/")
        String linkMan,
        @WebParam(name = "Tel", targetNamespace = "http://tempuri.org/")
        String tel,
        @WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "Email", targetNamespace = "http://tempuri.org/")
        String email,
        @WebParam(name = "Memo", targetNamespace = "http://tempuri.org/")
        String memo);

    /**
     * 
     * @param corpID
     * @param pwd
     * @return
     *     returns int
     */
    @WebMethod(operationName = "SelSum", action = "http://tempuri.org/SelSum")
    @WebResult(name = "SelSumResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SelSum", targetNamespace = "http://tempuri.org/", className = "msg.SelSum")
    @ResponseWrapper(localName = "SelSumResponse", targetNamespace = "http://tempuri.org/", className = "msg.SelSumResponse")
    public int selSum(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 
     * @param corpID
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetBalance", action = "http://tempuri.org/GetBalance")
    @WebResult(name = "GetBalanceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBalance", targetNamespace = "http://tempuri.org/", className = "msg.GetBalance")
    @ResponseWrapper(localName = "GetBalanceResponse", targetNamespace = "http://tempuri.org/", className = "msg.GetBalanceResponse")
    public String getBalance(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 
     * @param corpID
     * @param mobile
     * @param pwd
     * @param cell
     * @param content
     * @param sendTime
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Send", action = "http://tempuri.org/Send")
    @WebResult(name = "SendResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Send", targetNamespace = "http://tempuri.org/", className = "msg.Send")
    @ResponseWrapper(localName = "SendResponse", targetNamespace = "http://tempuri.org/", className = "msg.SendResponse")
    public int send(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "Content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "Cell", targetNamespace = "http://tempuri.org/")
        String cell,
        @WebParam(name = "SendTime", targetNamespace = "http://tempuri.org/")
        String sendTime);

    /**
     * 
     * @param corpID
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Get", action = "http://tempuri.org/Get")
    @WebResult(name = "GetResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Get", targetNamespace = "http://tempuri.org/", className = "msg.Get")
    @ResponseWrapper(localName = "GetResponse", targetNamespace = "http://tempuri.org/", className = "msg.GetResponse")
    public String get(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 
     * @param corpID
     * @param pwd
     * @return
     *     returns int
     */
    @WebMethod(operationName = "UnReg", action = "http://tempuri.org/UnReg")
    @WebResult(name = "UnRegResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UnReg", targetNamespace = "http://tempuri.org/", className = "msg.UnReg")
    @ResponseWrapper(localName = "UnRegResponse", targetNamespace = "http://tempuri.org/", className = "msg.UnRegResponse")
    public int unReg(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 
     * @param corpID
     * @param cardPwd
     * @param pwd
     * @param cardNo
     * @return
     *     returns int
     */
    @WebMethod(operationName = "ChargeUp", action = "http://tempuri.org/ChargeUp")
    @WebResult(name = "ChargeUpResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ChargeUp", targetNamespace = "http://tempuri.org/", className = "msg.ChargeUp")
    @ResponseWrapper(localName = "ChargeUpResponse", targetNamespace = "http://tempuri.org/", className = "msg.ChargeUpResponse")
    public int chargeUp(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "CardNo", targetNamespace = "http://tempuri.org/")
        String cardNo,
        @WebParam(name = "CardPwd", targetNamespace = "http://tempuri.org/")
        String cardPwd);

    /**
     * 
     * @param loginPwd
     * @param corpID
     * @param loginName
     * @param mmsBalance
     * @param smsBalance
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AgentChangeAccount", action = "http://tempuri.org/AgentChangeAccount")
    @WebResult(name = "AgentChangeAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AgentChangeAccount", targetNamespace = "http://tempuri.org/", className = "msg.AgentChangeAccount")
    @ResponseWrapper(localName = "AgentChangeAccountResponse", targetNamespace = "http://tempuri.org/", className = "msg.AgentChangeAccountResponse")
    public String agentChangeAccount(
        @WebParam(name = "LoginName", targetNamespace = "http://tempuri.org/")
        String loginName,
        @WebParam(name = "LoginPwd", targetNamespace = "http://tempuri.org/")
        String loginPwd,
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "SmsBalance", targetNamespace = "http://tempuri.org/")
        int smsBalance,
        @WebParam(name = "MmsBalance", targetNamespace = "http://tempuri.org/")
        int mmsBalance);

    /**
     * 
     * @param corpID
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "BalanceMMS", action = "http://tempuri.org/BalanceMMS")
    @WebResult(name = "BalanceMMSResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BalanceMMS", targetNamespace = "http://tempuri.org/", className = "msg.BalanceMMS")
    @ResponseWrapper(localName = "BalanceMMSResponse", targetNamespace = "http://tempuri.org/", className = "msg.BalanceMMSResponse")
    public String balanceMMS(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 
     * @param base64Content
     * @param extCode
     * @param corpID
     * @param mobile
     * @param pwd
     * @param title
     * @param sendTime
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendMMS", action = "http://tempuri.org/SendMMS")
    @WebResult(name = "SendMMSResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendMMS", targetNamespace = "http://tempuri.org/", className = "msg.SendMMS")
    @ResponseWrapper(localName = "SendMMSResponse", targetNamespace = "http://tempuri.org/", className = "msg.SendMMSResponse")
    public String sendMMS(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "Base64Content", targetNamespace = "http://tempuri.org/")
        String base64Content,
        @WebParam(name = "Title", targetNamespace = "http://tempuri.org/")
        String title,
        @WebParam(name = "ExtCode", targetNamespace = "http://tempuri.org/")
        String extCode,
        @WebParam(name = "SendTime", targetNamespace = "http://tempuri.org/")
        String sendTime);

    /**
     * 
     * @param base64Content
     * @param extCode
     * @param corpID
     * @param mobiles
     * @param pwd
     * @param title
     * @param sendTime
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "BatchSendMMS", action = "http://tempuri.org/BatchSendMMS")
    @WebResult(name = "BatchSendMMSResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BatchSendMMS", targetNamespace = "http://tempuri.org/", className = "msg.BatchSendMMS")
    @ResponseWrapper(localName = "BatchSendMMSResponse", targetNamespace = "http://tempuri.org/", className = "msg.BatchSendMMSResponse")
    public String batchSendMMS(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "Mobiles", targetNamespace = "http://tempuri.org/")
        String mobiles,
        @WebParam(name = "Base64Content", targetNamespace = "http://tempuri.org/")
        String base64Content,
        @WebParam(name = "Title", targetNamespace = "http://tempuri.org/")
        String title,
        @WebParam(name = "ExtCode", targetNamespace = "http://tempuri.org/")
        String extCode,
        @WebParam(name = "SendTime", targetNamespace = "http://tempuri.org/")
        String sendTime);

    /**
     * 
     * @param corpID
     * @param pwd
     * @param cell
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetReportFailMMS", action = "http://tempuri.org/GetReportFailMMS")
    @WebResult(name = "GetReportFailMMSResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetReportFailMMS", targetNamespace = "http://tempuri.org/", className = "msg.GetReportFailMMS")
    @ResponseWrapper(localName = "GetReportFailMMSResponse", targetNamespace = "http://tempuri.org/", className = "msg.GetReportFailMMSResponse")
    public String getReportFailMMS(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "cell", targetNamespace = "http://tempuri.org/")
        String cell);

    /**
     * 
     * @param corpID
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMMS", action = "http://tempuri.org/GetMMS")
    @WebResult(name = "GetMMSResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetMMS", targetNamespace = "http://tempuri.org/", className = "msg.GetMMS")
    @ResponseWrapper(localName = "GetMMSResponse", targetNamespace = "http://tempuri.org/", className = "msg.GetMMSResponse")
    public String getMMS(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 
     * @param corpID
     * @param cardPwd
     * @param pwd
     * @param cardNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ChargeUpMMS", action = "http://tempuri.org/ChargeUpMMS")
    @WebResult(name = "ChargeUpMMSResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ChargeUpMMS", targetNamespace = "http://tempuri.org/", className = "msg.ChargeUpMMS")
    @ResponseWrapper(localName = "ChargeUpMMSResponse", targetNamespace = "http://tempuri.org/", className = "msg.ChargeUpMMSResponse")
    public String chargeUpMMS(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "CardNo", targetNamespace = "http://tempuri.org/")
        String cardNo,
        @WebParam(name = "CardPwd", targetNamespace = "http://tempuri.org/")
        String cardPwd);

    /**
     * 
     * @param loginPwd
     * @param corpID
     * @param pass
     * @param loginName
     * @param mobile
     * @param memo
     * @param corpName
     * @param tel
     * @param linkMan
     * @param email
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AgentMakeAccount", action = "http://tempuri.org/AgentMakeAccount")
    @WebResult(name = "AgentMakeAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AgentMakeAccount", targetNamespace = "http://tempuri.org/", className = "msg.AgentMakeAccount")
    @ResponseWrapper(localName = "AgentMakeAccountResponse", targetNamespace = "http://tempuri.org/", className = "msg.AgentMakeAccountResponse")
    public String agentMakeAccount(
        @WebParam(name = "LoginName", targetNamespace = "http://tempuri.org/")
        String loginName,
        @WebParam(name = "LoginPwd", targetNamespace = "http://tempuri.org/")
        String loginPwd,
        @WebParam(name = "CorpName", targetNamespace = "http://tempuri.org/")
        String corpName,
        @WebParam(name = "LinkMan", targetNamespace = "http://tempuri.org/")
        String linkMan,
        @WebParam(name = "Tel", targetNamespace = "http://tempuri.org/")
        String tel,
        @WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "Email", targetNamespace = "http://tempuri.org/")
        String email,
        @WebParam(name = "Memo", targetNamespace = "http://tempuri.org/")
        String memo,
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pass", targetNamespace = "http://tempuri.org/")
        String pass);

    /**
     * 
     * @param corpID
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetReportSMS", action = "http://tempuri.org/GetReportSMS")
    @WebResult(name = "GetReportSMSResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetReportSMS", targetNamespace = "http://tempuri.org/", className = "msg.GetReportSMS")
    @ResponseWrapper(localName = "GetReportSMSResponse", targetNamespace = "http://tempuri.org/", className = "msg.GetReportSMSResponse")
    public String getReportSMS(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 
     * @param corpID
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetReportMMS", action = "http://tempuri.org/GetReportMMS")
    @WebResult(name = "GetReportMMSResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetReportMMS", targetNamespace = "http://tempuri.org/", className = "msg.GetReportMMS")
    @ResponseWrapper(localName = "GetReportMMSResponse", targetNamespace = "http://tempuri.org/", className = "msg.GetReportMMSResponse")
    public String getReportMMS(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 
     * @param corpID
     * @param mobile
     * @param pwd
     * @param cell
     * @param content
     * @param sendTime
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Send2", action = "http://tempuri.org/Send2")
    @WebResult(name = "Send2Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Send2", targetNamespace = "http://tempuri.org/", className = "msg.Send2")
    @ResponseWrapper(localName = "Send2Response", targetNamespace = "http://tempuri.org/", className = "msg.Send2Response")
    public String send2(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "Content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "Cell", targetNamespace = "http://tempuri.org/")
        String cell,
        @WebParam(name = "SendTime", targetNamespace = "http://tempuri.org/")
        String sendTime);

    /**
     * 
     * @param base64Content
     * @param extCode
     * @param corpID
     * @param mobile
     * @param pwd
     * @param title
     * @param sendTime
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendMMS2", action = "http://tempuri.org/SendMMS2")
    @WebResult(name = "SendMMS2Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendMMS2", targetNamespace = "http://tempuri.org/", className = "msg.SendMMS2")
    @ResponseWrapper(localName = "SendMMS2Response", targetNamespace = "http://tempuri.org/", className = "msg.SendMMS2Response")
    public String sendMMS2(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "Base64Content", targetNamespace = "http://tempuri.org/")
        String base64Content,
        @WebParam(name = "Title", targetNamespace = "http://tempuri.org/")
        String title,
        @WebParam(name = "ExtCode", targetNamespace = "http://tempuri.org/")
        String extCode,
        @WebParam(name = "SendTime", targetNamespace = "http://tempuri.org/")
        String sendTime);

    /**
     * 
     * @param corpID
     * @param mobile
     * @param pwd
     * @param cell
     * @param content
     * @param sendTime
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "BatchSend2", action = "http://tempuri.org/BatchSend2")
    @WebResult(name = "BatchSend2Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BatchSend2", targetNamespace = "http://tempuri.org/", className = "msg.BatchSend2")
    @ResponseWrapper(localName = "BatchSend2Response", targetNamespace = "http://tempuri.org/", className = "msg.BatchSend2Response")
    public String batchSend2(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "Content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "Cell", targetNamespace = "http://tempuri.org/")
        String cell,
        @WebParam(name = "SendTime", targetNamespace = "http://tempuri.org/")
        String sendTime);

    /**
     * 
     * @param corpID
     * @param mobile
     * @param pwd
     * @param cell
     * @param content
     * @param sendTime
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "IntlSend", action = "http://tempuri.org/IntlSend")
    @WebResult(name = "IntlSendResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IntlSend", targetNamespace = "http://tempuri.org/", className = "msg.IntlSend")
    @ResponseWrapper(localName = "IntlSendResponse", targetNamespace = "http://tempuri.org/", className = "msg.IntlSendResponse")
    public String intlSend(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "Content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "Cell", targetNamespace = "http://tempuri.org/")
        String cell,
        @WebParam(name = "SendTime", targetNamespace = "http://tempuri.org/")
        String sendTime);

    /**
     * 
     * @param base64Content
     * @param extCode
     * @param corpID
     * @param mobiles
     * @param pwd
     * @param title
     * @param sendTime
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "BatchSendMMS2", action = "http://tempuri.org/BatchSendMMS2")
    @WebResult(name = "BatchSendMMS2Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BatchSendMMS2", targetNamespace = "http://tempuri.org/", className = "msg.BatchSendMMS2")
    @ResponseWrapper(localName = "BatchSendMMS2Response", targetNamespace = "http://tempuri.org/", className = "msg.BatchSendMMS2Response")
    public String batchSendMMS2(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "Mobiles", targetNamespace = "http://tempuri.org/")
        String mobiles,
        @WebParam(name = "Base64Content", targetNamespace = "http://tempuri.org/")
        String base64Content,
        @WebParam(name = "Title", targetNamespace = "http://tempuri.org/")
        String title,
        @WebParam(name = "ExtCode", targetNamespace = "http://tempuri.org/")
        String extCode,
        @WebParam(name = "SendTime", targetNamespace = "http://tempuri.org/")
        String sendTime);

    /**
     * 
     * @param showNum
     * @param verifyCode
     * @param corpID
     * @param vtplId
     * @param mobile
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "VoiceNotify", action = "http://tempuri.org/VoiceNotify")
    @WebResult(name = "VoiceNotifyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "VoiceNotify", targetNamespace = "http://tempuri.org/", className = "msg.VoiceNotify")
    @ResponseWrapper(localName = "VoiceNotifyResponse", targetNamespace = "http://tempuri.org/", className = "msg.VoiceNotifyResponse")
    public String voiceNotify(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "verify_code", targetNamespace = "http://tempuri.org/")
        String verifyCode,
        @WebParam(name = "vtpl_id", targetNamespace = "http://tempuri.org/")
        String vtplId,
        @WebParam(name = "show_num", targetNamespace = "http://tempuri.org/")
        String showNum);

    /**
     * 
     * @param corpID
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "NotSend", action = "http://tempuri.org/NotSend")
    @WebResult(name = "NotSendResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "NotSend", targetNamespace = "http://tempuri.org/", className = "msg.NotSend")
    @ResponseWrapper(localName = "NotSendResponse", targetNamespace = "http://tempuri.org/", className = "msg.NotSendResponse")
    public String notSend(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 
     * @param corpID
     * @param jsonString
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "BatchContentSms", action = "http://tempuri.org/BatchContentSms")
    @WebResult(name = "BatchContentSmsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BatchContentSms", targetNamespace = "http://tempuri.org/", className = "msg.BatchContentSms")
    @ResponseWrapper(localName = "BatchContentSmsResponse", targetNamespace = "http://tempuri.org/", className = "msg.BatchContentSmsResponse")
    public String batchContentSms(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "JsonString", targetNamespace = "http://tempuri.org/")
        String jsonString);

    /**
     * 
     * @param corpID
     * @param mobile
     * @param pwd
     * @param cell
     * @param content
     * @param sendTime
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LinkSend", action = "http://tempuri.org/LinkSend")
    @WebResult(name = "LinkSendResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LinkSend", targetNamespace = "http://tempuri.org/", className = "msg.LinkSend")
    @ResponseWrapper(localName = "LinkSendResponse", targetNamespace = "http://tempuri.org/", className = "msg.LinkSendResponse")
    public String linkSend(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "Content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "Cell", targetNamespace = "http://tempuri.org/")
        String cell,
        @WebParam(name = "SendTime", targetNamespace = "http://tempuri.org/")
        String sendTime);

}
