package com.jhg.marketing.web.util.note;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LinkWSHttpGet", targetNamespace = "http://tempuri.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LinkWSHttpGet {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String helloWorld();

    /**
     * 
     * @param corpID
     * @param mobile
     * @param pwd
     * @param cell
     * @param content
     * @param sendTime
     * @return
     *     returns int
     */
    @WebMethod(operationName = "BatchSend")
    @WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
    public int batchSend(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID")
        String corpID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd")
        String pwd,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Mobile")
        String mobile,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Content")
        String content,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Cell")
        String cell,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "SendTime")
        String sendTime);

    /**
     * 
     * @param corpID
     * @param pwd
     * @param cell
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetReportFail")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String getReportFail(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID")
        String corpID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd")
        String pwd,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "cell")
        String cell);

    /**
     * 
     * @param corpID
     * @param mobile
     * @param memo
     * @param corpName
     * @param tel
     * @param pwd
     * @param linkMan
     * @param email
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Reg")
    @WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
    public int reg(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID")
        String corpID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd")
        String pwd,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpName")
        String corpName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "LinkMan")
        String linkMan,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Tel")
        String tel,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Mobile")
        String mobile,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Email")
        String email,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Memo")
        String memo);

    /**
     * 
     * @param corpID
     * @param newPwd
     * @param pwd
     * @return
     *     returns int
     */
    @WebMethod(operationName = "UpdPwd")
    @WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
    public int updPwd(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID")
        String corpID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd")
        String pwd,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "NewPwd")
        String newPwd);

    /**
     * 
     * @param corpID
     * @param mobile
     * @param memo
     * @param corpName
     * @param tel
     * @param pwd
     * @param linkMan
     * @param email
     * @return
     *     returns int
     */
    @WebMethod(operationName = "UpdReg")
    @WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
    public int updReg(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID")
        String corpID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd")
        String pwd,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpName")
        String corpName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "LinkMan")
        String linkMan,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Tel")
        String tel,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Mobile")
        String mobile,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Email")
        String email,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Memo")
        String memo);

    /**
     * 
     * @param corpID
     * @param pwd
     * @return
     *     returns int
     */
    @WebMethod(operationName = "SelSum")
    @WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
    public int selSum(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID")
        String corpID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd")
        String pwd);

    /**
     * 
     * @param corpID
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetBalance")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String getBalance(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID")
        String corpID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd")
        String pwd);

    /**
     * 
     * @param corpID
     * @param mobile
     * @param pwd
     * @param cell
     * @param content
     * @param sendTime
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Send")
    @WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
    public int send(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID")
        String corpID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd")
        String pwd,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Mobile")
        String mobile,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Content")
        String content,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Cell")
        String cell,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "SendTime")
        String sendTime);

    /**
     * 
     * @param corpID
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Get")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String get(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID")
        String corpID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd")
        String pwd);

    /**
     * 
     * @param corpID
     * @param pwd
     * @return
     *     returns int
     */
    @WebMethod(operationName = "UnReg")
    @WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
    public int unReg(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID")
        String corpID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd")
        String pwd);

    /**
     * 
     * @param corpID
     * @param cardPwd
     * @param pwd
     * @param cardNo
     * @return
     *     returns int
     */
    @WebMethod(operationName = "ChargeUp")
    @WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
    public int chargeUp(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID")
        String corpID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd")
        String pwd,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CardNo")
        String cardNo,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CardPwd")
        String cardPwd);

    /**
     * 
     * @param loginPwd
     * @param corpID
     * @param loginName
     * @param mmsBalance
     * @param smsBalance
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AgentChangeAccount")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String agentChangeAccount(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "LoginName")
        String loginName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "LoginPwd")
        String loginPwd,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID")
        String corpID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "SmsBalance")
        String smsBalance,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "MmsBalance")
        String mmsBalance);

    /**
     * 
     * @param corpID
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "BalanceMMS")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String balanceMMS(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID")
        String corpID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd")
        String pwd);

    /**
     * 
     * @param base64Content
     * @param extCode
     * @param corpID
     * @param mobile
     * @param pwd
     * @param title
     * @param sendTime
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendMMS")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String sendMMS(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID")
        String corpID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd")
        String pwd,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Mobile")
        String mobile,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Base64Content")
        String base64Content,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Title")
        String title,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ExtCode")
        String extCode,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "SendTime")
        String sendTime);

    /**
     * 
     * @param base64Content
     * @param extCode
     * @param corpID
     * @param mobiles
     * @param pwd
     * @param title
     * @param sendTime
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "BatchSendMMS")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String batchSendMMS(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID")
        String corpID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd")
        String pwd,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Mobiles")
        String mobiles,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Base64Content")
        String base64Content,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Title")
        String title,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ExtCode")
        String extCode,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "SendTime")
        String sendTime);

    /**
     * 
     * @param corpID
     * @param pwd
     * @param cell
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetReportFailMMS")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String getReportFailMMS(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID")
        String corpID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd")
        String pwd,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "cell")
        String cell);

    /**
     * 
     * @param corpID
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMMS")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String getMMS(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID")
        String corpID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd")
        String pwd);

    /**
     * 
     * @param corpID
     * @param cardPwd
     * @param pwd
     * @param cardNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ChargeUpMMS")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String chargeUpMMS(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID")
        String corpID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd")
        String pwd,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CardNo")
        String cardNo,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CardPwd")
        String cardPwd);

    /**
     * 
     * @param loginPwd
     * @param corpID
     * @param pass
     * @param loginName
     * @param mobile
     * @param memo
     * @param corpName
     * @param tel
     * @param linkMan
     * @param email
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AgentMakeAccount")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String agentMakeAccount(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "LoginName")
        String loginName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "LoginPwd")
        String loginPwd,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpName")
        String corpName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "LinkMan")
        String linkMan,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Tel")
        String tel,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Mobile")
        String mobile,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Email")
        String email,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Memo")
        String memo,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID")
        String corpID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pass")
        String pass);

    /**
     * 
     * @param corpID
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetReportSMS")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String getReportSMS(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID")
        String corpID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd")
        String pwd);

    /**
     * 
     * @param corpID
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetReportMMS")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String getReportMMS(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID")
        String corpID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd")
        String pwd);

    /**
     * 
     * @param corpID
     * @param mobile
     * @param pwd
     * @param cell
     * @param content
     * @param sendTime
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Send2")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String send2(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID")
        String corpID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd")
        String pwd,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Mobile")
        String mobile,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Content")
        String content,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Cell")
        String cell,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "SendTime")
        String sendTime);

    /**
     * 
     * @param base64Content
     * @param extCode
     * @param corpID
     * @param mobile
     * @param pwd
     * @param title
     * @param sendTime
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendMMS2")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String sendMMS2(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID")
        String corpID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd")
        String pwd,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Mobile")
        String mobile,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Base64Content")
        String base64Content,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Title")
        String title,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ExtCode")
        String extCode,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "SendTime")
        String sendTime);

    /**
     * 
     * @param corpID
     * @param mobile
     * @param pwd
     * @param cell
     * @param content
     * @param sendTime
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "BatchSend2")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String batchSend2(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID")
        String corpID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd")
        String pwd,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Mobile")
        String mobile,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Content")
        String content,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Cell")
        String cell,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "SendTime")
        String sendTime);

    /**
     * 
     * @param corpID
     * @param mobile
     * @param pwd
     * @param cell
     * @param content
     * @param sendTime
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "IntlSend")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String intlSend(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID")
        String corpID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd")
        String pwd,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Mobile")
        String mobile,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Content")
        String content,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Cell")
        String cell,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "SendTime")
        String sendTime);

    /**
     * 
     * @param base64Content
     * @param extCode
     * @param corpID
     * @param mobiles
     * @param pwd
     * @param title
     * @param sendTime
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "BatchSendMMS2")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String batchSendMMS2(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID")
        String corpID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd")
        String pwd,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Mobiles")
        String mobiles,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Base64Content")
        String base64Content,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Title")
        String title,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ExtCode")
        String extCode,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "SendTime")
        String sendTime);

    /**
     * 
     * @param showNum
     * @param verifyCode
     * @param corpID
     * @param vtplId
     * @param mobile
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "VoiceNotify")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String voiceNotify(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID")
        String corpID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd")
        String pwd,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Mobile")
        String mobile,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "verify_code")
        String verifyCode,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "vtpl_id")
        String vtplId,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "show_num")
        String showNum);

    /**
     * 
     * @param corpID
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "NotSend")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String notSend(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID")
        String corpID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd")
        String pwd);

    /**
     * 
     * @param corpID
     * @param jsonString
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "BatchContentSms")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String batchContentSms(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID")
        String corpID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd")
        String pwd,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "JsonString")
        String jsonString);

    /**
     * 
     * @param corpID
     * @param mobile
     * @param pwd
     * @param cell
     * @param content
     * @param sendTime
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LinkSend")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String linkSend(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID")
        String corpID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd")
        String pwd,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Mobile")
        String mobile,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Content")
        String content,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Cell")
        String cell,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "SendTime")
        String sendTime);

}
