
package com.jhg.marketing.web.util.hisInterface;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ICommonWeChatApi", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://khyy120.oicp.io/ICommonWeChatApi.asmx?wsdl")
public class ICommonWeChatApi
    extends Service
{

    private final static URL ICOMMONWECHATAPI_WSDL_LOCATION;
    private final static WebServiceException ICOMMONWECHATAPI_EXCEPTION;
    private final static QName ICOMMONWECHATAPI_QNAME = new QName("http://tempuri.org/", "ICommonWeChatApi");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://khyy120.oicp.io/ICommonWeChatApi.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ICOMMONWECHATAPI_WSDL_LOCATION = url;
        ICOMMONWECHATAPI_EXCEPTION = e;
    }

    public ICommonWeChatApi() {
        super(__getWsdlLocation(), ICOMMONWECHATAPI_QNAME);
    }

    public ICommonWeChatApi(WebServiceFeature... features) {
        super(__getWsdlLocation(), ICOMMONWECHATAPI_QNAME, features);
    }

    public ICommonWeChatApi(URL wsdlLocation) {
        super(wsdlLocation, ICOMMONWECHATAPI_QNAME);
    }

    public ICommonWeChatApi(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ICOMMONWECHATAPI_QNAME, features);
    }

    public ICommonWeChatApi(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ICommonWeChatApi(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ICommonWeChatApiSoap
     */
    @WebEndpoint(name = "ICommonWeChatApiSoap")
    public ICommonWeChatApiSoap getICommonWeChatApiSoap() {
        return super.getPort(new QName("http://tempuri.org/", "ICommonWeChatApiSoap"), ICommonWeChatApiSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICommonWeChatApiSoap
     */
    @WebEndpoint(name = "ICommonWeChatApiSoap")
    public ICommonWeChatApiSoap getICommonWeChatApiSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ICommonWeChatApiSoap"), ICommonWeChatApiSoap.class, features);
    }

    /**
     *
     * @return
     *     returns ICommonWeChatApiSoap
     */
    @WebEndpoint(name = "ICommonWeChatApiSoap12")
    public ICommonWeChatApiSoap getICommonWeChatApiSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "ICommonWeChatApiSoap12"), ICommonWeChatApiSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICommonWeChatApiSoap
     */
    @WebEndpoint(name = "ICommonWeChatApiSoap12")
    public ICommonWeChatApiSoap getICommonWeChatApiSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ICommonWeChatApiSoap12"), ICommonWeChatApiSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ICOMMONWECHATAPI_EXCEPTION!= null) {
            throw ICOMMONWECHATAPI_EXCEPTION;
        }
        return ICOMMONWECHATAPI_WSDL_LOCATION;
    }

}
